name: Deploy to Server

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Update server by ssh
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /hosting/lavka-partner-info

            git fetch origin master
            git reset --hard origin/master
            
            echo "üõë Remove container"
            docker rm -f lavka-info

            docker build -t lavka-info:latest .

            docker run -d --name lavka-info -p 3000:80 lavka-info:latest

      - name: Notify about error via Telegram Bot
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="‚ùå –î–µ–ø–ª–æ–π –≤ —Ä–µ–ø–æ–∑–∏—Ç–æ—Ä–∏–π *${{ github.repository }}*, –≤–µ—Ç–∫–∞ *${{ github.ref_name }}* –∑–∞–≤–µ—Ä—à–∏–ª—Å—è —Å –æ—à–∏–±–∫–æ–π!\n–ö–æ–º–º–∏—Ç: ${{ github.event.head_commit.message }}" \
          -d parse_mode=Markdown